### ISSUE TITLE
Getting more messages than max-length allows

### ISSUE THREAD

**Issue by antondalgren** [cloudamqp/avalanchemq#194] opened 2021-01-19 09:23 UTC
![image](https://user-images.githubusercontent.com/9164583/105014050-3b0c4a00-5a40-11eb-828f-9d0cdbb41334.png)

Cannot reproduce, more information needed.

**Comment by carlhoerberg** [comment] 2021-02-02 07:46
Closing it for now as we can't reproduce it anymore

**Closed by carlhoerberg** 2021-02-02 07:46 UTC
Labels: bug
